#FROM spark:4.0.0-scala2.13-java21-python3-ubuntu
# RUN apt update && \
#      apt install -y curl zip unzip 
# #     #rm -rf /var/lib/apt/lists/*
# RUN pip3 install  pyspark
# RUN curl -s "https://get.sdkman.io" | bash

# RUN bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install java 17.0.16-tem"

# RUN useradd -ms /bin/bash jupyter

# USER jupyter
# WORKDIR /home/user/jupyter

# RUN python3 -m venv .venv 
# RUN bash -c "source ./.venv/bin/activate"

FROM spark:4.0.0-scala2.13-java21-ubuntu

USER root
#RUN chown -R spark:spark /home/spark/

RUN set -ex; \
    apt-get update; \
    apt-get install -y python3 python3-pip curl zip unzip; \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install pyspark jupyterlab
    
RUN mkdir /home/spark
RUN chown -R spark:spark /home/spark/
USER spark